/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`

    id("com.gradleup.shadow") version "9.0.0-beta10"
}

repositories {
    mavenCentral()

    maven("https://repo.slne.dev/repository/maven-public/")
}

dependencies {
    compileOnlyApi(libs.paper.api)
    compileOnlyApi(libs.commandapi)
    compileOnlyApi(libs.placeholder.api)
    compileOnlyApi(libs.oraxen)
    compileOnlyApi(libs.betterhud.standard)
    compileOnlyApi(libs.betterhud.bukkit)
    compileOnlyApi(libs.betterhud.commands)
    compileOnlyApi(libs.znpc)
    compileOnlyApi(libs.chestprotect)

    api(libs.inventory.framework)
    api(libs.configurate.core)
    api(libs.configurate.yml)
}

group = "de.castcrafter"
version = "1.0-SNAPSHOT"

tasks {
    shadowJar {
        mergeServiceFiles()
        relocate(
            "com.github.stefvanschie.inventoryframework",
            "de.castcrafter.lootdrop.inventoryframework"
        )
        relocate("org.spongepowered", "de.castcrafter.lootdrop.spongepowered")
    }
}
description = "loot_drop"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}
