name: loot_drop
version: '${project.version}'
main: de.castcrafter.lootdrop.Main
api-version: '1.20'
depend:
  - CommandAPI
  - PlaceholderAPI
commands:
  copyloot:
    description: Copies the contents of the chest you are looking at.
    usage: /copyloot
  summonloot:
    description: Summons the loot drop at your position.
    usage: /summonloot
#  sealoot:
#    description: Summons a loot drop at your position.
#    usage: /sealoot